server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true  # 自我保护模式
    eviction-interval-timer-in-ms: 30000 #4eureka server清理无效节点的时间间隔
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/



spring:
  application:
    name: cloud-eureka
  security:
    user:
      name: admin
      password: admin

